# Generated by Django 6.1.1 on 2026-09-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True, verbose_name='CPF/CNPJ')),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cnj', models.CharField(max_length=25, unique=True, verbose_name='Número CNJ')),
                ('area', models.CharField(choices=[('trabalhista', 'Trabalhista'), ('civel', 'Cível'), ('previdenciario', 'Previdenciário')], max_length=20)),
                ('tribunal', models.CharField(blank=True, max_length=150, verbose_name='Tribunal/Vara')),
                ('fase', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('arquivado', 'Arquivado')], default='ativo', max_length=20)),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('honorarios', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('alerta_pendente', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='processos.cliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('origem', models.CharField(default='datajud', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='processos.processo')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
