# Generated by Django 6.1.1 on 2026-09-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='tribunal_alias',
            field=models.CharField(blank=True, help_text='Ex: trt2, tjsp, trf3 — usado para consultar a API do DataJud', max_length=20, verbose_name='Alias do tribunal (DataJud)'),
        ),
    ]
